# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2020-03-28 02:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Music',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='', max_length=50, verbose_name='音乐名')),
                ('price', models.DecimalField(decimal_places=2, default=0.0, max_digits=7, verbose_name='价格')),
                ('desc', models.CharField(default='', max_length=100, verbose_name='简介')),
            ],
        ),
    ]
