# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2020-04-11 00:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_number', models.CharField(db_index=True, default='', max_length=32, verbose_name='订单编号')),
                ('order_time', models.CharField(default='', max_length=20, verbose_name='订单创建时间')),
                ('name', models.CharField(default='', max_length=50, verbose_name='商品名称')),
                ('price', models.DecimalField(decimal_places=2, default=0.0, max_digits=7, verbose_name='商品单价')),
                ('count', models.IntegerField(default=0, verbose_name='购买数量')),
                ('img_path', models.ImageField(default='', upload_to='', verbose_name='图片路径')),
                ('total', models.DecimalField(decimal_places=2, default=0.0, max_digits=8, verbose_name='商品总价')),
                ('status', models.CharField(default='2', max_length=1, verbose_name='订单状态')),
            ],
        ),
    ]
