# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2020-04-11 01:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='order_number',
            field=models.CharField(db_index=True, default='', max_length=32, unique=True, verbose_name='订单编号'),
        ),
    ]
